name: Greeting
on: push
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "Hello, world!"
      - name: greet the world again
        run: echo "Hello, world!"
   